### PR TITLE
fix: system tray causing crash on linux

### LINKED ISSUE #232: Crashes on Linux at `InitSystemTray`
**Describe the bug**
Compiles and begins to run, window shows, but then crashes when it reaches `InitSystemTray`.

**To Reproduce**
1. `flutter run -d linux`

**Expected behavior**
Runs without crashing.

**Additional context**
Fedora 40 KDE

<details>
<summary>Crash log</summary>

```
Launching lib/main.dart on Linux in debug mode...
package:media_kit_libs_linux registered.
Connecting to VM Service at ws://127.0.0.1:33499/PMTonZmAwUk=/ws
[GETX] Instance "DesktopSystemTray" has been created
[GETX] Instance "DesktopSystemTray" has been initialized
flutter: Configure AudioServiceLinux.
[GETX] Instance "LibrarySongsController" has been created
[GETX] Instance "LibrarySongsController" has been initialized
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
[GETX] Instance "AudioHandler" has been created
flutter: setQueue() has not been implemented.
flutter: Requested property Identity from org.mpris.MediaPlayer2
2
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
2
flutter: GetPosition(): 0:00:00.000000
flutter: Requested property Position from org.mpris.MediaPlayer2.Player
flutter: GetPosition(): 0:00:00.000000
flutter: Requested property Position from org.mpris.MediaPlayer2.Player
flutter: GetPosition(): 0:00:00.000000
[GETX] Instance "ThemeController" has been created
[GETX] Instance "ThemeController" has been initialized
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
flutter: [Harmony Music]: Home
[GETX] Instance "PlayerController" has been created
[GETX] Instance "MusicServices" has been created
[GETX] Instance "MusicServices" has been initialized
[GETX] Instance "PlayerController" has been initialized
[GETX] Instance "SettingsScreenController" has been created
[GETX] Instance "SettingsScreenController" has been initialized
[GETX] Instance "HomeScreenController" has been created
[GETX] Instance "HomeScreenController" has been initialized
flutter: [Harmony Music]: player
[GETX] Instance "Downloader" has been created
[GETX] Instance "Downloader" has been initialized
flutter: Requested property Metadata from org.mpris.MediaPlayer2.Player
flutter: Requested property Position from org.mpris.MediaPlayer2.Player
flutter: GetPosition(): 0:00:00.000000
flutter: Requested property PlaybackStatus from org.mpris.MediaPlayer2.Player
flutter: Requested property CanPause from org.mpris.MediaPlayer2.Player
flutter: Requested property CanPlay from org.mpris.MediaPlayer2.Player
flutter: Requested property CanGoNext from org.mpris.MediaPlayer2.Player
flutter: Requested property CanGoPrevious from org.mpris.MediaPlayer2.Player
flutter: Requested property CanSeek from org.mpris.MediaPlayer2.Player
flutter: Requested property LoopStatus from org.mpris.MediaPlayer2.Player
flutter: Requested property Shuffle from org.mpris.MediaPlayer2.Player
flutter: Requested property Volume from org.mpris.MediaPlayer2.Player
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
method call InitSystemTray
Lost connection to device.

Exited.
```

</details>

### PR DESCRIPTION
**Pull request by Merrit**
The [system_tray](https://pub.dev/packages/system_tray) package appears abandoned, with no update or comments for 13 months. The issue this PR fixes is due to a known bug in the system_tray package: https://github.com/antler119/system_tray/issues/64

This PR replaces the system_tray package with the [tray_manager](https://pub.dev/packages/tray_manager) package, which is actively maintained and doesn't cause the crash. `tray_manager` has beem around for 3+ years and had a release just 11 days ago. `tray_manager` is also a sibling package to the `window_manager` package already being used.

Resolves #232

### CODE REVIEW

File: lib/utils/system_tray.dart [hunk 1]
```diff
@@ -23,79 +23,89 @@ class DesktopSystemTray extends GetxService {
...
+  @override
+  void onTrayIconRightMouseDown() {
+    if (GetPlatform.isWindows) {
+      trayManager.popUpContextMenu();
+    } else {
+      windowManager.show();
+    }
+
+    super.onTrayIconRightMouseDown();
+  }
```
Comment (Merrit) [inline lib/utils/system_tray.dart:108]: I'm not certain this is the click behaviour we want, I simply reproduced what we currently had.

Personally, I think left-click to show/hide and right-click for context menu sounds quite appropriate and expected (speaking as a full-time Linux user).
